# Generated by Django 3.1 on 2020-08-19 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('visible', models.BooleanField(default=True)),
                ('order_priority', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-order_priority'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sidebar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('visible', models.BooleanField(default=True)),
                ('order_priority', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-order_priority'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SidebarEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('visible', models.BooleanField(default=True)),
                ('order_priority', models.IntegerField(default=0)),
                ('link', models.CharField(max_length=100, null=True)),
                ('sidebar_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entries.sidebar')),
            ],
            options={
                'ordering': ['-order_priority'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('visible', models.BooleanField(default=True)),
                ('order_priority', models.IntegerField(default=0)),
                ('time', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entries.section')),
            ],
            options={
                'ordering': ['-order_priority'],
                'abstract': False,
            },
        ),
    ]
