# Generated by Django 3.1 on 2020-08-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebarentry',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
