# Generated by Django 3.1 on 2020-08-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_auto_20200819_1430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name': 'Entries'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'Section'},
        ),
        migrations.AlterModelOptions(
            name='sentry',
            options={'verbose_name': 'Sidebar entries'},
        ),
        migrations.AlterModelOptions(
            name='sidebar',
            options={'verbose_name': 'Sidebar sections'},
        ),
        migrations.AddField(
            model_name='sentry',
            name='space_bottom',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='entry',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
