# Generated by Django 3.1 on 2020-08-20 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0005_auto_20200820_1222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-order_priority'], 'verbose_name': 'Entrie'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['-order_priority'], 'verbose_name': 'Section'},
        ),
        migrations.AlterModelOptions(
            name='sentry',
            options={'ordering': ['-order_priority'], 'verbose_name': 'Sidebar entrie'},
        ),
        migrations.AlterModelOptions(
            name='sidebar',
            options={'ordering': ['-order_priority'], 'verbose_name': 'Sidebar section'},
        ),
    ]
