# Generated by Django 3.1 on 2020-08-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0006_auto_20200820_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='SiteName', max_length=15)),
                ('sub_title', models.CharField(default='Curriculum Vitae', max_length=30)),
                ('introtext', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
    ]
